/* ============================================================
   AI-MOCK.JS — Mock AI for Assignment Generation & Auto-Grading
   Phase 1: Simulates AI responses without real API calls.
   Phase 2: Replace with real Claude/Gemini API calls.
   ============================================================ */

const AI = (() => {

  async function callBackend(endpoint, payload) {
    const apiBase = typeof window !== 'undefined' && window.API_BASE !== undefined ? window.API_BASE : 'http://127.0.0.1:8080';
    const res = await fetch(`${apiBase}/api/${endpoint}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    if (!res.ok) throw new Error(`Backend Error: ${res.statusText}`);
    const data = await res.json();
    if (data.success === false) throw new Error(`Backend Error: ${data.error}`);
    return data.data;
  }

  async function generateAssignment({ coText, rbtLevel, topic, numQuestions=2, maxMarks=10 }) {
    const data = await callBackend('generate-assignment', { topic, level: rbtLevel, num: numQuestions, marks: maxMarks });
    return {
      questions: data.questions,
      rubrics: data.rubrics,
      generatedAt: new Date().toISOString(),
      model: 'Gemini-1.5-Pro',
      note: 'This content was generated by LangChain Agent. Please review and edit before publishing.',
    };
  }

  async function gradeSubmission({ submissionText, rubrics, maxMarks }) {
    const data = await callBackend('grade', { text: submissionText, rubrics, maxMarks });
    return {
      ...data,
      gradedAt: new Date().toISOString(),
      model: 'Gemini-1.5-Pro',
      note: 'AI-generated grade. Faculty must review and approve before publishing.',
    };
  }

  async function generateTeachingPhilosophy({ courseName, deptVision, deptMission }) {
    return await callBackend('philosophy', { courseName, deptVision: deptVision||'', deptMission: deptMission||'' });
  }

  async function analyzeBlooms(cos) {
    return await callBackend('analyze-blooms', { cos });
  }

  async function autoMapCOPO(cos, pos, psoDefs) {
    return await callBackend('auto-map-copo', { cos, pos, pso_defs: psoDefs });
  }

  async function generateRemedialPlan(studentName, weakCOs) {
    return await callBackend('remedial', { student: studentName, weakCOs });
  }


  async function extractSyllabusFromText(text) {
    return await callBackend('extract-syllabus', { text });
  }

  async function generateCOsFromSyllabus(syllabusText) {
    return await callBackend('generate-cos', { syllabus: syllabusText });
  }

  function getUsageStats() {

    return { used: 0, max: 9999, pct: 0, enabled: true };
  }

  async function callRealAPI(prompt, model='gemini-1.5-pro') {
    return await callBackend('chat', { message: prompt, context: '' });
  }

  return { generateAssignment, gradeSubmission, generateTeachingPhilosophy, analyzeBlooms, autoMapCOPO, generateRemedialPlan, extractSyllabusFromText, generateCOsFromSyllabus, getUsageStats, callRealAPI };
})();
